<?php

namespace GepurIt\LdapBundle\Repository;

use Doctrine\ORM\EntityRepository;
use GepurIt\LdapBundle\Entity\LdapResource;

/**
 * LdapResourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LdapResourceRepository extends EntityRepository
{
    /**
     * @return LdapResource[] get full information (with related models)
     */
    public function findAllFull(): array
    {
        $query = $this->createQueryBuilder('resource')
            ->addSelect('roleAccesses')
            ->addSelect('role')
            ->leftJoin('resource.roleAccesses', 'roleAccesses')
            ->leftJoin('roleAccesses.role', 'role')
            ->getQuery();

        return $query->getResult();
    }

    /**
     * @param string $resourceName
     *
     * @return LdapResource|null
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findOneFullByResource(string $resourceName): ?LdapResource
    {
        $query = $this->createQueryBuilder('resource')
            ->addSelect('roleAccesses')
            ->addSelect('role')
            ->leftJoin('resource.roleAccesses', 'roleAccesses')
            ->leftJoin('roleAccesses.role', 'role')
            ->where('resource.resource = :resourceName')->setParameter('resourceName', $resourceName)
            ->getQuery();

        /** @var LdapResource|null $resource */
        $resource = $query->getOneOrNullResult();

        return $resource;
    }

    /**
     * @param string $resourceName
     *
     * @return null|LdapResource
     */
    public function findOneByResource(string $resourceName): ?LdapResource
    {
        /** @var LdapResource $resourceName */
        $resourceName = $this->findOneBy(['resource' => $resourceName]);

        return $resourceName;
    }

    /**
     * @param string $role
     *
     * @return bool
     */
    public function existsByResource(string $role): bool
    {
        return (null !== $this->findOneByResource($role));
    }
}
