<?php
/**
 * Created by PhpStorm.
 * User: Andrii Yakovlev
 * Date: 08.12.17
 */
declare(strict_types=1);

namespace GepurIt\LdapBundle\Repository;

use Doctrine\ORM\EntityRepository;
use GepurIt\LdapBundle\Entity\LdapRole;

/**
 * LdapRoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LdapRoleRepository extends EntityRepository
{
    /**
     * @param string $role
     *
     * @return LdapRole|null
     */
    public function findOneByRole(string $role): ?LdapRole
    {
        /** @var LdapRole $role */
        $role = $this->findOneBy(['role' => $role]);

        return $role;
    }

    /**
     * @param string $role
     *
     * @return bool
     */
    public function existsByRole(string $role): bool
    {
        return (null !== $this->findOneByRole($role));
    }
}
