<?php
/**
 * Created by PhpStorm.
 * User: Andrii Yakovlev
 * Date: 08.12.17
 */
declare(strict_types=1);

namespace GepurIt\LdapBundle\Repository;

use Doctrine\ORM\EntityRepository;
use GepurIt\LdapBundle\Entity\LdapRoleAccess;
use Symfony\Component\Security\Core\Authentication\Token\TokenInterface;

/**
 * LdapRoleAccessRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LdapRoleAccessRepository extends EntityRepository
{
    /**
     * @param TokenInterface $token
     * @return LdapRoleAccess[]
     */
    public function findByToken(TokenInterface $token): array
    {
        $query = $this->createQueryBuilder('ldapRoleAccess')
            ->addSelect('resource')
            ->addSelect('role')
            ->join('ldapRoleAccess.resource', 'resource')
            ->join('ldapRoleAccess.role', 'role')
            ->where('role.role IN (:roles)')->setParameter('roles', $token->getRoleNames())
            ->getQuery();

        /** @var LdapRoleAccess[] $ldapRolesAccess */
        $ldapRolesAccess = $query->getResult();

        return $ldapRolesAccess;
    }
}
