services:
    GepurIt\LdapBundle\Command\:
        autowire: true
        resource: '../../Command/*'
        tags: ['console.command']

    GepurIt\LdapBundle\Security\AccessProvider:
        autowire: true

    GepurIt\LdapBundle\Security\LdapVoter:
        autowire: true
        tags:
            - { name: 'security.voter' }

    GepurIt\LdapBundle\Ldap\LdapConnection:
        class: GepurIt\LdapBundle\Ldap\LdapConnection
        autowire: true

    GepurIt\LdapBundle\Security\LdapGroupsProvider:
        autowire: true

    GepurIt\LdapBundle\Security\LdapResourcesProvider:
        autowire: true

    GepurIt\LdapBundle\Security\PermissionProvider:
        autowire: true

    GepurIt\LdapBundle\Entry\EntryHelper:
        autowire: true

    GepurIt\LdapBundle\Security\LdapUserProvider:
        autowire: true

    GepurIt\LdapBundle\Security\UserProfileProvider:
        autowire: true

    GepurIt\LdapBundle\Security\FailureHandler:
        autowire: true

    GepurIt\LdapBundle\Security\LoginSuccessHandler:
        autowire: true

    GepurIt\LdapBundle\Security\LogoutLogHandler:
        autowire: true

    GepurIt\LdapBundle\Security\LogoutCleanApiKeyHandler:
        autowire: true

    GepurIt\LdapBundle\Security\LogoutSuccessHandler:
        autowire: true

    GepurIt\LdapBundle\Security\ApiKeyAuthenticator:
        autowire: true

    GepurIt\LdapBundle\Security\ApiKeyUserProvider:
        autowire: true

    ldap.user_provider: '@GepurIt\LdapBundle\Security\LdapUserProvider'
    ldap.login.failure_handler: '@GepurIt\LdapBundle\Security\FailureHandler'
    ldap.login.success_handler: '@GepurIt\LdapBundle\Security\LoginSuccessHandler'
    ldap.logout.log_handler: '@GepurIt\LdapBundle\Security\LogoutLogHandler'
    ldap.logout.api_key_handler: '@GepurIt\LdapBundle\Security\LogoutCleanApiKeyHandler'
    ldap.logout.success_handler: '@GepurIt\LdapBundle\Security\LogoutSuccessHandler'
    ldap.api_key.user_provider: '@GepurIt\LdapBundle\Security\ApiKeyUserProvider'
    ldap.api_key.authenicator: '@GepurIt\LdapBundle\Security\ApiKeyAuthenticator'
