services:
    GepurIt\LdapBundle\Command\:
        autowire: true
        resource: '../../Command'
        tags: ['console.command']

    GepurIt\LdapBundle\Repository\:
        autowire: true
        resource: '../../Repository'
        tags: ['doctrine.repository_service']

    GepurIt\LdapBundle\Security\AccessProvider:
        autowire: true

    GepurIt\LdapBundle\Security\LdapVoter:
        autowire: true
        tags:
            - { name: 'security.voter' }

    GepurIt\LdapBundle\Ldap\LdapConnection:
        class: GepurIt\LdapBundle\Ldap\LdapConnection
        autowire: true

    GepurIt\LdapBundle\Security\LdapGroupsProvider:
        autowire: true

    GepurIt\LdapBundle\Security\LdapResourcesProvider:
        autowire: true

    GepurIt\LdapBundle\Security\PermissionProvider:
        autowire: true

    GepurIt\LdapBundle\Entry\EntryHelper:
        autowire: true

    GepurIt\LdapBundle\Security\UserProfileProvider:
        autowire: true

    GepurIt\LdapBundle\Logout\LogoutHandler:
        autowire: true

    GepurIt\LdapBundle\Logout\LogoutSuccessHandler:
        autowire: true

  # new edition
    GepurIt\LdapBundle\Ldap\UserProvider:
        autowire: true

    GepurIt\LdapBundle\Contracts\ErpUserProviderInterface: '@GepurIt\LdapBundle\Ldap\UserProvider'

    GepurIt\LdapBundle\Guard\LdapAuthenticator:
        autowire: true

    GepurIt\LdapBundle\ApiKey\ApiKeyStorage:
        autowire: true

    GepurIt\LdapBundle\Guard\ApiKeyAuthenticator:
        autowire: true